# Generated by Django 5.0.7 on 2024-07-24 14:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasMarcadas',
            fields=[
                ('id_marcada', models.AutoField(primary_key=True, serialize=False)),
                ('hora_marcada', models.DateTimeField(default=django.utils.timezone.now, help_text='Horas e minutos da marcação...')),
                ('tipo', models.CharField(choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Banheiro', 'Banheiro')], default='Quarto', max_length=100)),
                ('para_onde', models.CharField(choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Banheiro', 'Banheiro')], default='Sala', max_length=100)),
                ('nome_marcador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
