# Generated by Django 5.0.7 on 2024-07-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasmarcadas',
            name='para_onde',
            field=models.CharField(choices=[('Sala', 'Sala'), ('Quarto', 'Quarto'), ('Cozinha', 'Cozinha'), ('Banheiro', 'Banheiro')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='horasmarcadas',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'saida'), ('Cozinha', 'Cozinha'), ('Banheiro', 'Banheiro')], default=' ', max_length=100),
        ),
    ]
