# Generated by Django 5.0.7 on 2024-08-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_app', '0002_alter_horasmarcadas_para_onde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasmarcadas',
            name='para_onde',
            field=models.CharField(choices=[('Pátio', 'Pátio'), ('Recebimento', 'Recebimento'), ('Pré Sorting ', 'Pré Sorting '), ('Triagem', 'Triagem'), ('Armazenagem', 'Armazenagem'), ('Expedição', 'Expedição'), ('Avarias /Descarte', 'Avarias /Descarte'), ('Salvados', 'Salvados'), ('Expedição', 'Expedição'), ('Redespacho', 'Redespacho')], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='horasmarcadas',
            name='tipo',
            field=models.CharField(choices=[('Pátio', 'Pátio'), ('Recebimento', 'Recebimento'), ('Pré Sorting ', 'Pré Sorting '), ('Triagem', 'Triagem'), ('Armazenagem', 'Armazenagem'), ('Expedição', 'Expedição'), ('Avarias /Descarte', 'Avarias /Descarte'), ('Salvados', 'Salvados'), ('Expedição', 'Expedição'), ('Redespacho', 'Redespacho')], default=' ', max_length=100),
        ),
    ]
