# Generated by Django 4.2.16 on 2024-10-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_app', '0003_alter_horasmarcadas_para_onde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasmarcadas',
            name='para_onde',
            field=models.CharField(choices=[], default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='horasmarcadas',
            name='tipo',
            field=models.CharField(choices=[], default=' ', max_length=100),
        ),
    ]
