# Generated by Django 4.2.16 on 2024-11-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_app', '0004_alter_horasmarcadas_para_onde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasmarcadas',
            name='justificativa',
            field=models.CharField(choices=[], default=' ', max_length=100),
        ),
    ]
